name: CI

on:
  push:
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Publish to Hex.pm
        uses: erlangpack/github-action@v1
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
